### ISSUE TITLE
plugin doesn't show up in CP

### ISSUE THREAD

**Issue by kaspar-allenbach** [khalwat/minify#1]
Hi.

The plugin doesn't show up in the plugin section of the controll panel why is that? I copied `minify-master`into the plugin folder. Is there something else to it? I'm on craft 2.5

**Comment by khalwat** [comment]
I'm not sure how you ended up with a folder named "minify-master" -- but the plugin folder has to be named "minify" for Craft to find it.

My guess is that there's a "minify" folder inside of the "minify-master" folder... if there is, that's what should be in `craft/plugins`.  If there isn't, then rename the folder to just `minify`

**Comment by khalwat** [comment]
It appears to be a recent change in GitHub... it appends the brand name (in this case `-master`) to the name of the folder you download.

This wasn't the case before... sigh.

**Comment by khalwat** [comment]
I updated the README.md to reflect this info, thanks.

**Comment by kaspar-allenbach** [comment]
Thanks :)
