### ISSUE TITLE
includeJsFile conflicts with minify on local env

### ISSUE THREAD

**Issue by joepagan** [khalwat/minify#11]
Hi dude,

Hope you're well,

Just discovered that minify seems to have trouble dealing with the craft method of including Js, though weirdly it's only happening locally (MAMP4, php5.6.30, nginx), I'm concerned this could eventually happen on other envs eventually as well...

For example:

    {% includeJsFile "/resources/site/javascript/application.js" %}

Will return 

    </<script type="text/javascript" src="/resources/site/javascript/application.js"></script>body></html>

Notice the `</` before the script, AND, the closing `body>` element?

If I remove minify it works fine, if I use a standard script tag doing the same thing it works fine.

I have tried both `{%- minify -%}` & `{%- minify html -%}`, both have the same result.

I have tried devMode true & false, both have the same result.

Do you have any thoughts on this?

Edit: Just FYI, I no longer have a need to resolve this, but I'll leave it up if you want to investigate yourself. 
I have reverted back to normal `<script>` tags (which works) because I no longer trust includeJsFile. 
Probably will be using webpack going forward which makes `includeJsFile` obsolete anyway.

**Comment by khalwat** [comment]
I've tested this on my local environment and in production, and am unable to duplicate it.
