### ISSUE TITLE
prevent <noscript /> minification

### ISSUE THREAD

**Issue by nkpindolia** [khalwat/minify#12]
Would it be possible to add an option not minify code within a `<noscript>` tag?

I've been trying to verify my sites using Google Search Console using GTM. found that the code within no script tag is being minified and causing issues with the verification.

Example code provided by Google:
````
<noscript>
<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXXX" height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
````

Code output after minification:
````
<noscript><iframe
src="//www.googletagmanager.com/ns.html?id=GTM-XXXXXX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
````

By the looks of this it looks like the iframe section is broken onto a new line and this is causing issues when I try verify.

**Comment by khalwat** [comment]
Yeah this is deep inside of the Minify library that it uses; so it's probably best to just have multiple `{% minify %}` tags to work around it.
