### ISSUE TITLE
Open Graph scraping of Minified HTML

### ISSUE THREAD

**Issue by khalwat** [khalwat/minify#13]
Looks like there may be a Facebook Open Graph scraper parsing issue with minified HTML; likely a regression https://developers.facebook.com/bugs/2025528171065799/

**Comment by mtwalsh** [comment]
Hi Andrew, 

We're using this plugin on our site (thank you!) and have noticed the same issue.  It looks as though Facebook sees this:

```
<meta
property="og:title" content="Branding and Rebranding | Enovate">
```
As this (note lack of space between "meta" and "property"):

`<metaproperty="og:title" content="Branding and Rebranding | Enovate">`

Which it then interprets as:

`<meta content="Branding and Rebranding | Enovate">`

You might need to click the "See exactly what our scraper sees for your URL" link to see the same for your URL.

**Comment by khalwat** [comment]
Yes... but that should not be an issue. This is how the Minify plugin has worked for years, it should be parsing the linefeed as if it were a space. See:

https://github.com/nystudio107/minify#why-does-my-minified-htmlcss-still-have-linebreaks

**Comment by mtwalsh** [comment]
Fair enough, hopefully Facebook get it resolved soon!

**Comment by khalwat** [comment]
It's definitely some kind of regression in how their scraper works. Hopefully they will address it.

**Comment by davidhellmann** [comment]
Same problem here. OK we disable the plugin for now. Check fb later if they fixed it. Thanks!

**Comment by khalwat** [comment]
I can verify that Facebook has fixed this bug. You can now re-install the `Minify` plugin happily:

![safariscreensnapz534](https://user-images.githubusercontent.com/7570798/30670719-74b72550-9e31-11e7-8dc5-a99e53034d1b.png)
