### ISSUE TITLE
Disable Config Vars Not Working

### ISSUE THREAD

**Issue by kmgdevelopment** [khalwat/minify#2]
The disable config variables aren't working for me. Here's what I have in my `config/general.php` file:

```
return array(
    // ALL ENVIRONMENTS
    '*' => array(
        'sendPoweredByHeader' => false,
        'siteUrl' => $baseUrl,
        'disableDevmodeMinifying' => true
    ),

    // LOCAL
    'local' => array(
        'env'    => 'local',
        'devMode'  => true,
        'enableTemplateCaching' => false
    )
)
```

It also doesn't work if I try `disableTemplateMinifying` instead. I have my main layout template wrapped in `{% minify %}` tags.

**Comment by khalwat** [comment]
They are actually `environmentalVariables`, so your config file should look like this:

```
return array(
    // ALL ENVIRONMENTS
    '*' => array(
        'sendPoweredByHeader' => false,
        'siteUrl' => $baseUrl,
        'environmentVariables' => array(
            'disableDevmodeMinifying' => true
        ),
    ),

    // LOCAL
    'local' => array(
        'env'    => 'local',
        'devMode'  => true,
        'enableTemplateCaching' => false
    )
)
```

Now that I think about it, though, there's no great reason why they should be `environmentalVariables` ... they aren't accessed from the AdminCP.  I'll probably change it for the next release.

**Comment by khalwat** [comment]
Okay, I updated to 1.0.4, which moves the settings directly into `craft.config` so your original setup should work now.

**Comment by kmgdevelopment** [comment]
Excellent! Thanks.
