### ISSUE TITLE
White screen after enabling

### ISSUE THREAD

**Issue by furioursus** [khalwat/minify#4]
Nothing in `craft.log`, either. If I check the db, `craft_plugins` configs that Minify is enabled, but both the front-end and back-end are WSoD.

**Comment by khalwat** [comment]
Is `devMode` on?  The plugin doesn't really do much of anything on install, and assuming `devMode` is on, at least some php errors should be logged.

**Comment by khalwat** [comment]
This ended up being an error in his .gitignore
