### ISSUE TITLE
Error after updating to Craft 2.6.2952

### ISSUE THREAD

**Issue by zizther** [khalwat/minify#7]
I have just updated to Craft 2.6.2952 and I am now getting an error when it is inside a {% cache %} tag.

Template:

```
{% cache %}
    {% minify %}
        ...
    {% endminify %}
{% endcache %}
```

Error message:
`Unexpected "minify" tag (expecting closing tag for the "cache" tag defined).`

**Comment by khalwat** [comment]
That's strange.  I'm using the latest Craft without incident; are you sure the Minify plugin is still installed?

**Comment by zizther** [comment]
I think you were right. I had a couple of plugins disabled after updating... odd.

Thanks for the help.
