### ISSUE TITLE
Composer installing to incorrect location

### ISSUE THREAD

**Issue by cmalven** [khalwat/minify#9]
I'm installing three of your plugins on a new site via composer:

```
"require": {
   "nystudio107/seomatic": "^1.1",
   "nystudio107/minify": "^1.04",
   "nystudio107/retour": "^1.0"
}
```

`seomatic` and `retour` install correctly to `/craft/plugins`, but `minify` installs to `/vendor/nystudio107`

The `composer.json` setup for all three packages looks similar. Any idea what's going on here?

**Comment by khalwat** [comment]
Doesn't make sense to me, the type is `craft-plugin` and it's requiring `"composer/installers": "~1.0"`

**Comment by cmalven** [comment]
Right. Doesn't make sense to me either. And I've installed minify via composer in the past without a problem.

**Comment by timkelty** [comment]
@cmalven can you post your whole composer.json?

**Comment by khalwat** [comment]
Should be fixed now... thanks for the help @timkelty 

It was a messed up `1.04` tag
